DEFAULTS:
  db:
    adapter: mysql2
    hostname: localhost
    username: root

development:
  db:
    database: foo_development

test:
  db:
    database: foo_test

production:
  db:
    database: foo_production
