# NOTE: Confy will refuse to load this file if it were added to your project's git repo!
development:
  db:
    password: secret

test:
  db:
    password: secret

production:
  db:
    password: topsecret
